### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by Cxyofficial** [mxyooR/Auto_mys_goods#1]
{"data":null,"message":"未登录","retcode":-2007} {"data":null,"message":"未登录","retcode":-2007} {"data":null,"message":"未登录","retcode":-2007} {"data":null,"message":"未登录","retcode":-2007} {"data":null,"message":"未登录","retcode":-2007}

**Comment by mxyooR** [comment]
你是抓包拿的token吗

**Comment by Cxyofficial** [comment]
> 你是抓包拿的token吗

是 我用了下gui版 把gui版的ck扔到无gui版里头又能用了
